/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/stocks/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Stock Data */
        get: operations["get_stock_data_stocks__ticker__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** StockHistory */
        StockHistory: {
            /**
             * Open
             * @description Opening price of the stock
             */
            Open: number;
            /**
             * High
             * @description Highest price of the stock during the period
             */
            High: number;
            /**
             * Low
             * @description Lowest price of the stock during the period
             */
            Low: number;
            /**
             * Close
             * @description Closing price of the stock
             */
            Close: number;
            /**
             * Volume
             * @description Trading volume
             */
            Volume: number;
            /**
             * Dividends
             * @description Dividend amount
             */
            Dividends: number;
            /**
             * Stocksplits
             * @description Stock split ratio
             */
            StockSplits: number;
            /**
             * Date
             * @description Date of the stock data
             */
            Date?: string | null;
        };
        /** StockResponse */
        StockResponse: {
            /**
             * Ticker
             * @description Stock ticker symbol
             */
            ticker: string;
            /**
             * Company
             * @description Company name
             */
            company: string;
            /**
             * Current Price
             * @description Current stock price
             */
            current_price: number | null;
            /**
             * Market Cap
             * @description Market capitalization
             */
            market_cap: number | null;
            /**
             * History
             * @description Historical stock data
             */
            history: components["schemas"]["StockHistory"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_stock_data_stocks__ticker__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
